import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="px-[25%] py-0 flex-row">
          <p className="py-4 w-full justify-center flex text-3xl  font-bold">
            My Blog
          </p>
          <Navbar menu={["Post", "Users"]} />
          {children}
        </div>
      </body>
    </html>
  );
}
